### PR TITLE
fix subclass/superclass typing requirement mismatch

### PR DESCRIPTION
**Pull request by TallTed**
*In the summary table,* change the type requirements of the superclasses (`Credential` and `Presentation`) to match the type requirements of the subclasses (`VerifiableCredential` and `VerifiablePresentation`).

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/685.html" title="Last updated on Jul 11, 2019, 2:55 PM UTC (e158b5c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/685/96dc09e...e158b5c.html" title="Last updated on Jul 11, 2019, 2:55 PM UTC (e158b5c)">Diff</a>

### CODE REVIEW

**Comment by David-Chadwick** [comment]
Isnt this a substantive change, as it is effectively changing a MUST into a MAY?

**Comment by TallTed** [comment]
No, because the table is summarizing statements made elsewhere.  The [relevant body text](https://github.com/w3c/vc-data-model/blob/96dc09e869069bcf5f9c36e039f81e32c3cb8b04/index.html#L1282) which is summarized in the table requires only `a type property`, not `a type and a subtype`.

**Comment by David-Chadwick** [comment]
@TallTed And because the statements elsewhere have changed substantially so the table needs to change to sync up.

**Comment by David-Chadwick** [comment]
Guys this is not an editorial, it is a substantive change of a MUST to a MAY. I object to this merging on these grounds

**Comment by brentzundel** [comment]
@David-Chadwick the associated text from the spec:
> All credentials, presentations, and encapsulated objects MUST specify, or be associated with, additional more narrow types (like UniversityDegreeCredential, for example) so software systems can process this additional information. *The specification of these additional more narrow types could be done in the object within which the additional information is found, rather than at a higher level such as the type property of the credential or presentation.*

The bold text makes clear that any additional properties may be specified at a lower level than the `type` property of the verifiable credential or presentation, therefore having a more specific type in the `type` property of a verifiable credential or presentation is optional. The more specific type may be specified in the `type` property of the `credentialSubject`, for example.

**Comment by msporny** [comment]
In addition to what @brentzundel says above, the CR spec published on March 28th states:
> All credentials, presentations, and encapsulated objects MUST specify, **or be associated with**, additional more narrow types (like UniversityDegreeCredential, for example) so software systems can process this additional information.

**Comment by David-Chadwick** [comment]
@msporny . Correct. And the following sentence in March 28th attempts to define what associated with means, viz

"When processing encapsulated objects defined in this specification, (for example, objects **associated with** the credentialSubject object or deeply nested therein), software systems SHOULD use the type information specified in encapsulating objects higher in the hierarchy. Specifically, an encapsulating object, such as credential, SHOULD convey the associated object types so that verifiers can quickly determine the contents of an associated object based on the encapsulating object type."

So the March 28 version makes it very clear that
a) all objects MUST specify their more narrow types or be associated with this type
and
b) associate with refers to the higher encapsulating objects and to nothing else (like an implicit type)

So objects SHOULD specify their types in their higher encapsulating types, but if not, MAY specify them in the objects themselves. But there is NO get out clause saying that objecs do not need to specify their types.

**Pull request merged**
