### PR TITLE
Migrate VC-JWT section to dedicated specification.

### PR DESCRIPTION
**Pull request by msporny**
This PR migrates the VC-JWT section in the VC data model specification to a dedicated specification. The corresponding PR into the destination specification can be found here: https://github.com/w3c/vc-jwt/pull/1

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/899.html" title="Last updated on Aug 14, 2022, 8:05 PM UTC (775af20)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/899/8d73553...775af20.html" title="Last updated on Aug 14, 2022, 8:05 PM UTC (775af20)">Diff</a>

### CODE REVIEW

**Review by peacekeeper — APPROVED** [review]
Similar to https://github.com/w3c/vc-data-model/pull/900, I assume this is done after FPWD is out and the actual JWT-related content has been moved into the [VC-JWT spec](https://w3c.github.io/vc-jwt/).

**Comment by peacekeeper** [comment]
Should this PR also update the following reference?

https://github.com/w3c/vc-data-model/blob/ae31f28f3356046b3466f08aaec56c3ce100d2e7/index.html#L1712

**Comment by msporny** [comment]
> Should this PR also update the following reference?

Good catch, yes it should. I'll make that update before merging.

**Review by OR13 — APPROVED** [review]

**Review by Sakurann — APPROVED** [review]

**Review by brentzundel — APPROVED** [review]

**Review by dlongley — APPROVED** [review]

**Review by mprorock — APPROVED** [review]

**Review by selfissued — APPROVED** [review]
LGTM

**Comment by msporny** [comment]
@peacekeeper wrote:
> Should this PR also update the following reference?
> https://github.com/w3c/vc-data-model/blob/ae31f28f3356046b3466f08aaec56c3ce100d2e7/index.html#L1712

Fixed in 775af200979abb5376c32d68fa7b8ee710f91e42.

**Comment by msporny** [comment]
Substantive, multiple reviews, changes requested and made, no objections, merging.

**Pull request merged**
