### PR TITLE
Add nbf registered claim to v2 context 

### PR DESCRIPTION
**Pull request by OR13**
This PR adds `nbf` to the v2 context.

```json
{
  "@context": [
    "https://w3id.org/traceability/v1", {
    "nbf": {
      "@id": "https://www.iana.org/assignments/jwt#iat",
      "@type": "https://www.w3.org/2001/XMLSchema#nonNegativeInteger"
    }
    }
  ],
  "type": "Organization",
  "name": "Bartell Inc 🔥",
  "description": "Realigned maximized alliance",
  "nbf": 123
}
```

...

```json
{
  "@type": "https://schema.org/Organization",
  "https://schema.org/description": "Realigned maximized alliance",
  "https://schema.org/name": "Bartell Inc 🔥",
  "https://www.iana.org/assignments/jwt#iat": {
    "@type": "https://www.w3.org/2001/XMLSchema#nonNegativeInteger",
    "@value": 123
  }
}
```

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1221.html" title="Last updated on Aug 4, 2023, 1:03 PM UTC (8ddfc8d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1221/7e6e996...8ddfc8d.html" title="Last updated on Aug 4, 2023, 1:03 PM UTC (8ddfc8d)">Diff</a>

### CODE REVIEW

**Review by decentralgabe — APPROVED** [review]

**Comment by davidlehn** [comment]
The example should have `nbf` instead of `iat`.

**Review by dmitrizagidulin — APPROVED** [review]

**Review by msporny — CHANGES_REQUESTED** [review]
PR includes commits on main, needs a rebase.

**Review by davidlehn — CHANGES_REQUESTED** [review]
Extraneous commits should be removed so only the single relevant commit remains.

**Review by brentzundel — APPROVED** [review]

**Comment by brentzundel** [comment]
@msporny and @davidlehn since this PR is quite simple (and the changes made were originally in a single commit) I think it should be fine to squash and merge back down to a single commit.

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
Normative, multiple reviews, no changes requested, no objections, merging.

**Pull request merged**
