### PR TITLE
Mike is at Self-Issued Consulting

### PR DESCRIPTION
**Pull request by selfissued**
***
<a href="https://pr-preview.s3.amazonaws.com/selfissued/vc-data-model/pull/1368.html" title="Last updated on Dec 1, 2023, 9:12 PM UTC (e972e1e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1368/1d7b554...selfissued:e972e1e.html" title="Last updated on Dec 1, 2023, 9:12 PM UTC (e972e1e)">Diff</a>

### CODE REVIEW

**Comment by msporny** [comment]
Purely editorial, merging.

**Comment by iherman** [comment]
My apologies that I did not spot this earlier. "Self-issued consulting" is not a W3C member, so I am not sure if it is appropriate listing it as an affiliation for editorship. In this WG Mike is an Invited Expert, and does not represent, officially, his employer, so he should either be listed as Invited Expert or without affiliation. 

(Sorry, I do not make the rules...)

**Comment by iherman** [comment]
cc @selfissued @msporny

**Comment by msporny** [comment]
Acknowledged, my suggestion is that we just list the Invited Experts w/o a corporate affiliation.

**Comment by iherman** [comment]
I would prefer "invited expert". That is the official terminology at W3C. Nothing at all is also acceptable.

**Comment by msporny** [comment]
Alright, @selfissued back to you then... what would you prefer beside your name, "Invited Expert" or nothing?

**Pull request merged**
