### PR TITLE
Remove "proof" clauses from initial examples

### PR DESCRIPTION
**Pull request by selfissued**
This PR needs to be merged to add the vc-jose-cose examples at https://github.com/w3c/vc-jose-cose/pull/162#pullrequestreview-1662677250

***
<a href="https://pr-preview.s3.amazonaws.com/selfissued/vc-data-model/pull/1308.html" title="Last updated on Oct 13, 2023, 6:12 PM UTC (7878d79)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1308/286c2b2...selfissued:7878d79.html" title="Last updated on Oct 13, 2023, 6:12 PM UTC (7878d79)">Diff</a>

### CODE REVIEW

**Review by OR13 — APPROVED** [review]

**Review by decentralgabe — APPROVED** [review]

**Review by Sakurann — APPROVED** [review]
probably a separate PR, but I would also make it clearer that `4.9 Securing Verifiable Credentials` section is applicable to data integrity but not jose-cose

**Comment by peacekeeper** [comment]
I find it confusing if the first example in the spec says "A simple example of a verifiable credential", but then what's shown is not a verifiable credential?

**Review by awoie — APPROVED** [review]
Agree with those changes.

**Review by dwaite — APPROVED** [review]

**Comment by andresuribe87** [comment]
I agree with the comment on https://github.com/w3c/vc-data-model/pull/1308#issuecomment-1751918366

My concrete suggestion is to replace `A simple example of a verifiable credential` with `An example credential, which when secured, becomes a verifiable credential`. Alternatively, `A simple example of the contents of a verifiable credential`

**Comment by peacekeeper** [comment]
I agree with @andresuribe87 's suggestion to improve the title of the example.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-10-11-vcwg#section1-4) on 2023-10-11

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.4. Remove "proof" clauses from initial examples (pr vc-data-model#1308)

_See github pull request [vc-data-model#1308](https://github.com/w3c/vc-data-model/pull/1308)._




**Manu Sporny:** Orie raised this to remove the Data Integrity proofs from the initial examples. It has multiple positive reviews, I will probably +1 this as well. There is an open question here, which is, we have examples in the specifications that show how later examples are secured using both DI and, in theory, VC-JOSE-COSE.  
… The general question to the group is: Do we want to continue to do that. One of the complaints that we had early on is that we want complete examples.  
… Agree that example 1 is probably the wrong place to put that, but do we want examples throughout the spec to show how to secure in at least two different ways.  

**Brent Zundel:** It makes sense to me, to remove the `proof` property in earlier examples and adding it later to show using it with DI. Particularly because those later examples can be done alongside showing VC-JOSE-COSE securing mechanisms as well.  

> *David Chadwick:* I think examples will be very good for future readers.

**Dave Longley:** +1 to brent.  
… +1 for having full examples in the spec eventually.  

> *Manu Sporny:* +1 to having at least /some/ examples in the spec of fully verifiable VCs..

**Dave Longley:** but not having them be the very first one.  

**Brent Zundel:** Anything more to discuss on that PR?  
… As long as there remain from DI examples we're good?  

> *Dmitri Zagidulin:* as long as we clearly label it as "Unsigned/unsecured input document" or something similar.

**Brent Zundel:** I'll keep going.  

> *Brent Zundel:* subtopics: [https://github.com/w3c/vc-data-model/pull/1305](https://github.com/w3c/vc-data-model/pull/1305).

**Brent Zundel:** This PR removes the CL signature example, which though this makes me sad, it makes sense. I will probably +1 this one myself.  
… Urge folks to review as well.  

**Manu Sporny:** Yeah, this PR will probably go in because we don't have examples of CL signatures today. I will note that Greg Bernstein has raised PRs on the VC-DI-BBS specification to define it using the new format.  
… My expectation is that if we do get BBS in decent enough shape we can reinject an unlinkable signature into this part of the specification. That's my expectation.  

**Dave Longley:** +1 to that expectation.  

**Brent Zundel:** That's my understanding as well. We're hoping that folks can step up and serve as the example as the way to do this with ZKP.  

**Greg Bernstein:** That's looking in pretty good shape.  
… I raised some issues using the ECDSA-SD primitives -- I was able to reuse the ones from that spec.  
… I tried it on VC-DI-BBS and it looked good.  
… Along with using JSON pointers to specify mandatory and selective fields.  
… I went through the whole exercise of putting BBS together with the SD primitives (core functions) and adding a bit to ensure unlinkability.  
… The editors are kind of changing, so there are no reviewers on that PR but I'd like to get people to look at things.  

**Brent Zundel:** Thank you Greg, my hope is that as we move on from the other items as they go into CR we can spend more time on BBS (VC-DI-BBS).  

</details>

**Comment by OR13** [comment]
I don't see any objections to merging this in the meeting minutes, seems like it was generally well received and I have updated the title based on the suggestion in: https://github.com/w3c/vc-data-model/pull/1308#issuecomment-1758400051

**Comment by OR13** [comment]
5 approvals, no objections, open for 1 week, suggestions requested and applied merging.

**Pull request merged**
