### PR TITLE
Automatic generation of the vocab files via github actions

### PR DESCRIPTION
**Pull request by iherman**
A long-standing issue: this PR adds a github action file so that the official RDF vocabulary can be updated through the modification of the vocabulary.yml file, and the ttl/jsonld/html files are generated automatically using the [yml2vocab](https://github.com/w3c/yml2vocab) script.

Note that the setup is such that the final files are pushed into the `gh-pages` branch and not the `main` branch (in agreement with @msporny). This means that this PR should only be merged when the repository is slightly reorganized by making the `gh-pages` branch the target of the Github pages feature. That also means that the 'main' branch does not conain the jsonld/ttl/html files any more.

### CODE REVIEW

**Comment by iherman** [comment]
@msporny one warning: I am not sure how these things work: if this PR is merged will that merge automatically start the github action by virtue of merging? There is a bootstrap question here. The reason I am asking is that the merge would remove the vocabulary.{html,ttl,jsonld} files from the main repository, and not sure if they will appear right away in the `gh-pages` branch. Just to be on the safe side, once you merge the PR you should run the action manually...

**Comment by msporny** [comment]
> @msporny, I am not sure how these things work: if this PR is merged will that merge automatically start the github action by virtue of merging?

No, I think it'll need to be run manually the first time. I also don't expect us to get this right the first time. There are complications here (that we will deal w/ after the merge), specifically around making sure that the {html,ttl,jsonld} files are generated on both the gh-pages branch as well as during publication via Echidna. That is, there will have to be TWO workflows that generate the {html,ttl,jsonld} files. This is all do-able, and I'll take the time to make it work during the next merge cycle (in 7 days).

Thank you for putting this together, it'll make updating the vocabulary files much easier.

**Review by msporny — APPROVED** [review]

**Review by decentralgabe — APPROVED** [review]

**Review by dlongley — APPROVED** [review]

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-01-11-vcwg#section2-8) on 2023-01-11

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.8. Automatic generation of the vocab files via github actions (pr vc-data-model#1006)

_See github pull request [vc-data-model#1006](https://github.com/w3c/vc-data-model/pull/1006)._




**Manu Sporny:** Automatically generating vocabulary in PR 1006..  
… Ivan wrote tools for autogenerating vocab..  

**Ivan Herman:** It should not be merged until the repo is updated; the github pages would then rely on the `gh-pages` branch rather than `main`..  

**Manu Sporny:** Will fix the repo before merging..  

**Ivan Herman:** There are details to be fixed manually..  

</details>

**Review by brentzundel — APPROVED** [review]

**Comment by msporny** [comment]
Editorial, multiple reviews, changes requested (once merge occurs), no objections, merging.

**Pull request merged**
