### PR TITLE
Add new section on Subject.NE.Holder

### PR DESCRIPTION
**Pull request by David-Chadwick**
***
<a href="https://pr-preview.s3.amazonaws.com/David-Chadwick/vc-data-model/pull/134.html" title="Last updated on Mar 20, 2018, 10:52 PM GMT (604eb4c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/134/805722f...David-Chadwick:604eb4c.html" title="Last updated on Mar 20, 2018, 10:52 PM GMT (604eb4c)">Diff</a>

### CODE REVIEW

**Comment by davidlehn** [comment]
Copying comments over from https://github.com/w3c/vc-data-model/pull/122:
- This commit has a `.DS_Store` file added. Please remove it and force push an update. I just created a PR https://github.com/w3c/vc-data-model/pull/142 to help ignore such cruft in the future.
- The graphics should be converted to an editable format like SVG before merging this.
- The JSON in the text should have proper formatting and indentation to be easier to read.

**Comment by David-Chadwick** [comment]
@davidlehn As I said before I do not have any software that can create the diagram in the SVG format you require, so I used jpeg, which displays perfectly OK in my browser. But I am perfectly happy for you to reformat the diagram in any format that is acceptable to you.

**Comment by msporny** [comment]
Google Draw can export images as SVG and is what we use for most of our specification diagrams.

**Comment by David-Chadwick** [comment]
@msporny Thanks, I have managed to do that

**Comment by burnburn** [comment]
@msporny can you help @David-Chadwick with any remaining formatting issues so we can merge?

**Comment by msporny** [comment]
Closing this PR as its superseded by #169.

**Pull request closed without merging**
