### PR TITLE
Setting-up-echidna

### PR DESCRIPTION
**Pull request by iherman**
Simple echidna script, no other action is used (so far?) in this repository.

~Note: if the main branch of the repository is changed from `v2.0` to `main`, the relevant reference in line 6 must be changed.~

(The repository secret for W3C_TR_TOKEN has already been created.)

### CODE REVIEW

**Review by deniak — APPROVED** [review]

**Comment by iherman** [comment]
@msporny you to choose the time of merging this, knowing that as soon as it is done, every newly merged PR gets published...

**Comment by msporny** [comment]
> @msporny, you should to choose the time of merging this, knowing that as soon as it is done, every newly merged PR gets published...

Let's plan on letting the VCWG know this is happening during the call today, and then merging after the call.

**Review by msporny — APPROVED** [review]

**Comment by iherman** [comment]
> > @msporny, you should to choose the time of merging this, knowing that as soon as it is done, every newly merged PR gets published...
> 
> Let's plan on letting the VCWG know this is happening during the call today, and then merging after the call.

+1.

I am on vacations right now, so I do not know when I will look at this next time. Ie: I let you do the merge when you feel like it😀

**Review by brentzundel — APPROVED** [review]

**Review by mkhraisha — APPROVED** [review]

**Comment by iherman** [comment]
Back from vacations... @brentzundel @msporny @Sakurann, o.k. to merge this, ie, to make auto-publishing a reality?

**Comment by brentzundel** [comment]
> Back from vacations... @brentzundel @msporny @Sakurann, o.k. to merge this, ie, to make auto-publishing a reality?

yes please

**Comment by Sakurann** [comment]
Yes, please

**Pull request merged**
