### PR TITLE
Auto-generate context and vocabulary digests.

### PR DESCRIPTION
**Pull request by msporny**
This PR upgrades the specification to auto-generate the cryptographic digests for context and vocabulary files so that we no longer have to worry about the cryptographic digests getting out of sync with updates to the various documents. The digests have been updated to align with openssl digest output to make it easier for developers to verify the digests using common tooling available to them.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1499.html" title="Last updated on Jun 2, 2024, 6:55 PM UTC (6959f9f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1499/a3cdff1...6959f9f.html" title="Last updated on Jun 2, 2024, 6:55 PM UTC (6959f9f)">Diff</a>

### CODE REVIEW

**Review by dlongley — APPROVED** [review]
I think this is fine ... though I wonder whether we actually want to make this static when we go to REC. We can decide that later.

**Review by iherman — APPROVED** [review]
At some point in the future, we should move these scripts to the W3C space. But it is not urgent.

**Comment by msporny** [comment]
@dlongley wrote:
> I wonder whether we actually want to make this static when we go to REC. 

When the REC is published, the values will be static. The thing that is published to REC-space is a static copy of the specification (with the hashes locked in as plain text).

@iherman wrote:
> At some point in the future, we should move these scripts to the W3C space. But it is not urgent.

The scripts are already in W3C space, as a part of respec-vc. :)

**Review by decentralgabe — APPROVED** [review]

**Review by brentzundel — APPROVED** [review]

**Review by longpd — APPROVED** [review]

**Review by TallTed — APPROVED** [review]

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-05-vcwg#section5-4) on 2024-06-05

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.4. Auto-generate context and vocabulary digests. (pr vc-data-model#1499)

_See github pull request [vc-data-model#1499](https://github.com/w3c/vc-data-model/pull/1499)._




**Manu Sporny:** just a heads up on another PR (1499), we have an extension to respec that allows us to autogenerate these hashes.  
… the group said we would like these hashes to be easily generated by command line tool.  
… easiest thing to do is hex digest of openSSL command.  
… if folks don't like this approach please make it known in the PR.  
… this also makes it so we don't need to keep syncing the hex digests, guaranteed they will match what is published for context/vocab files.  
… I will assert that we are in pretty good shape to be done with this specification, maybe a handful of leftover issues.  
… once those are addressed I am asserting that we are pretty much done unless something amazing comes up.  
… one modulo to that is the security disclosure we are waiting on.  

</details>

**Comment by msporny** [comment]
Editorial, multiple positive reviews, no changes requested, no objections, merging.

**Pull request merged**
