### PR TITLE
New claim-example-2.svg

### PR DESCRIPTION
**Pull request by chaals**
- cleanly accessibly coded

### CODE REVIEW

**Review by kdenhartog — APPROVED** [review]

**Comment by kdenhartog** [comment]
We're currently targeting V1.1 branch which has a conflict in the README at the moment. Would you mind adding this change off the V1.1 branch instead to remove the conflicts? Huge thanks for taking the time to update these as well!

**Comment by chaals** [comment]
> Would you mind adding this change off the V1.1 branch instead

Will do - hopefully get to it today...

**Comment by kdenhartog** [comment]
Alternatively, I can pull this into PR #806 and take care of making sure this gets through

**Comment by chaals** [comment]
@kdenhartog if you can pull these changes through from here, that would be a help. I've probably run out of time for working on them for the next little while :S

**Comment by kdenhartog** [comment]
Will do, thanks for taking the time to build these and get some accessibility labels added to them as well!

**Comment by kdenhartog** [comment]
Pulled these into #733 and added you as a co-author. Thanks for putting these together. I'll go ahead and close this one now.

**Comment by chaals** [comment]
Thanks very much for the help @kdenhartog

**Pull request closed without merging**
