### PR TITLE
Migrate Data Integrity section to dedicated specification.

### PR DESCRIPTION
**Pull request by msporny**
This PR migrates the data integrity section into a dedicated specification.

DO NOT MERGE this until the Data Integrity specification is migrated into the VCWG.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/900.html" title="Last updated on Aug 14, 2022, 8:23 PM UTC (17c8957)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/900/893fa58...17c8957.html" title="Last updated on Aug 14, 2022, 8:23 PM UTC (17c8957)">Diff</a>

### CODE REVIEW

**Comment by iherman** [comment]
Is your intention of putting this into the spec _before_ it goes out to FPWD? I would prefer not; do that only when a FPWD is out for DI (using then a proper reference).

**Comment by msporny** [comment]
> Is your intention of putting this into the spec _before_ it goes out to FPWD? I would prefer not; do that only when a FPWD is out for DI (using then a proper reference).

Nope, all PRs I've raised since last Wednesday are for AFTER the FPWD.

**Review by peacekeeper — APPROVED** [review]
+1 to this after FPWD is out and Data Integrity has been migrated into VCWG.

**Review by OR13 — APPROVED** [review]

**Review by Sakurann — APPROVED** [review]

**Review by brentzundel — APPROVED** [review]

**Review by iherman — APPROVED** [review]

**Review by dlongley — APPROVED** [review]

**Comment by msporny** [comment]
Substantive, multiple reviews, [VCDM v2.0 FPWD](https://w3c.github.io/vc-data-model/) is published, no objections, merging.

**Pull request merged**
