### PR TITLE
Updated privacy language in diagram

### PR DESCRIPTION
**Pull request by andresuribe87**
This PR fixes https://github.com/w3c/vc-data-model/issues/1148 by slightly tweaking the language.

### CODE REVIEW

**Review by brentzundel — APPROVED** [review]

**Comment by TallTed** [comment]
I cannot edit the SVG source in this PR, but I have two suggested changes, removing RFC normative language, and matching capitalization of the rest of the illustration.

1. line 70, from —
   ```
   <text x="380" y="385" font-weight="bold">May not preserve privacy</text>
   ```
   — to —
   ```
   <text x="380" y="385" font-weight="bold">might NOT preserve privacy</text>
   ```

2. line 75, from —
   ```
   <text x="540" y="495" font-weight="bold">MAY preserve privacy</text>
   ```
   — to —
   ```
   <text x="540" y="495" font-weight="bold">MIGHT preserve privacy</text>
   ```

**Review by OR13 — COMMENTED** [review]
Probably want to avoid normative language, even in diagrams, suggest "might" or something similar... Good PR though.

**Comment by TallTed** [comment]
> Probably want to avoid normative language, even in diagrams, suggest "might" or something similar... 

Yeah, that's what's in [my suggestion, above](https://github.com/w3c/vc-data-model/pull/1174#issuecomment-1613928956)...

**Review by msporny — COMMENTED** [review]
Thanks for the PR! Please make the changes requested by @TallTed and @OR13 so we can merge the PR.

**Comment by andresuribe87** [comment]
Thanks @TallTed ! Applied in 7e36c77

**Review by msporny — APPROVED** [review]

**Review by decentralgabe — APPROVED** [review]

**Comment by msporny** [comment]
Editorial, multiple reviews, changes requested and made, no objections, merging.

**Pull request merged**
