### PR TITLE
Add proofPurpose requirement to spec. Fixes #103.

### LINKED ISSUE #103: Property name for bunding credentials in a profile?
We've had a discussion item come up in the Credentials CG where we're trying to determine the best name for the set of ways a Decentralized ID may issue verifiable credentials (Issuing suites), vs. the container name for verifiable credentials (here are my credentials). Currently, the options are:

* issue (downside is similarity to `issuer` property)
* credential (downside is this could be confused with application/purpose)
* issuing (a bit strange - term is a verb)
* issuingSuite (verbose, but may be a good pattern... e.g. authenticationSuite, encryptionSuite, issuingSuite, etc.)

So, maybe it would be best for nouns to hold stuff that you'd associate with "things you own" and "...Suite" would be used for "ways to perform actions". Fundamentally, we need to harmonize these terms in the VC Data Model and the DID specification.

### LINKED ISSUE #118: Data Model in Context of Keys, Signatures & Countersignatures
One of my challenges with the current data model focus of the WG is how it connects to the signatures of that data model. As an implementor, I find that confuses me when I consider claim + one or more signatures. 

Lets take a simple verifiable claim (from the [Verifiable Claims Playground](https://w3c-vc.github.io/playground/), which may not be current): 

```
{
  "@context": "https://schema.org/",
  "claim": {
    "id": "did:ALICE",
    "name": "Alice",
    "knows": {
      "id": "did:BOB",
      "name": "Bob"
    }
  }
}
```

When signed by one of the signing keys that is available from Alice's set of DID signing keys, it is a claim from an issuer, and has the trust level / authority that you give to that issuer. Is a claim signed any other way invalid?

When both signed by one of the signing keys that is available from Alice's set of DID signing keys AND SEPARATELY by one of the signing keys that is available from Bob's set of DID signing keys, I think this may have greater authority, as if you trust either Bob or Alice it has trust level authority of them individually, but with both signatures it has the trust authority of both.

If signed by Alice, and the entire structure (including signature) is signed by Bob, what does that mean differently than the previous?

When signed ONLY by one of the signing keys that is available from Bob's set of signing keys, but not Alice's, what is it? 

When it also signed by a third party (in addition to either Alice's or Bob's keys), that could be a witness claim.

But when it is signed by a third party (w/o Alice's or Bob's keys), what is that? An evidence claim?

When a signed claim above also has a time signature in it (a verifiable time stamp), what does that mean?

I presume if it was signed by an otherwise valid key, but not one that is designated as a signing key, then that claim should be considered invalid?

So in general, as an implementor, how do I know that the signing expresses the intent of the signer about the claim?

### PR DESCRIPTION
**Pull request by msporny**
Fixes #118.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/155.html" title="Last updated on Apr 7, 2018, 6:24 PM GMT (7dc8330)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/155/23bd58b...7dc8330.html" title="Last updated on Apr 7, 2018, 6:24 PM GMT (7dc8330)">Diff</a>

### CODE REVIEW

**Comment by nage** [comment]
+1 As per the discussion, making this a checked field provided by the signer for signature suites that require it, does appear to help signature schemes that don't differentiate at a more fundamental level.

**Comment by msporny** [comment]
Clarify that proofPurpose is optional, then pull in the PR.

**Comment by msporny** [comment]
Fixes #118.

**Comment by msporny** [comment]
TODO: Clarify that proofPurpose is optional, then pull in the PR.

**Pull request merged**
