### PR TITLE
Revise "Profile" concept to "Presentation", per F2F consensus

### LINKED ISSUE #163: Change VerifiableProfile to VerifiablePresentation
Based on discussion at the VCWG F2F in 2018, there was consensus to rename the "Verifiable Profile" to "Verifiable Presentation" to support use cases like ZKPs and to provide a different identifier for the presentation vs. the subject being identified.

### PR DESCRIPTION
**Pull request by msporny**
This PR changes the concept of a "Profile" to a "Presentation" based on the consensus achieved at the VCWG F2F in San Francisco 2018. Fixes #163.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/171.html" title="Last updated on May 8, 2018, 1:41 PM GMT (dea3a49)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/171/d15bcaf...dea3a49.html" title="Last updated on May 8, 2018, 1:41 PM GMT (dea3a49)">Diff</a>

### CODE REVIEW

**Comment by stonematt** [comment]
LGTM

**Comment by David-Chadwick** [comment]
LGTM

**Comment by msporny** [comment]
Blocking on @nage's review.

**Comment by msporny** [comment]
This PR is blocking a large series of editorial changes I need to make as a result of @vieillevigne's review comments (and there are a LOT of them). 

I'm pulling it in since 1) there have been no objections so far (and lots of support), 2) because it just executes on what the VCWG agreed to in the F2F meeting, and 3) because @nage is very busy and will probably not have time to review for another two weeks.

If there are objections after the fact, we'll deal with those in a separate PR.

**Pull request merged**
