### PR TITLE
Remove "holder" from "VerifiableCredential"

### PR DESCRIPTION
**Pull request by OR13**
Sorta related - https://github.com/w3c/vc-data-model/issues/959

### CODE REVIEW

**Comment by OR13** [comment]
We also need to remove https://www.w3.org/2018/credentials/#holder from here perhaps, only the "VerifiableCredential" part...

> Union of: cred:VerifiableCredential cred:VerifiablePresentation

to:

> Union of: cred:VerifiablePresentation

**Comment by iherman** [comment]
> We also need to remove https://www.w3.org/2018/credentials/#holder from here perhaps, only the "VerifiableCredential" part...
> 
> > Union of: cred:VerifiableCredential cred:VerifiablePresentation
> 
> to:
> 
> > Union of: cred:VerifiablePresentation

See #1078. We should not forget to merge that one before this if there is a consensus to merge.

**Comment by awoie** [comment]
IMO, we should remove all normative language on holder from the vocab too unless there is normative statements on holder in the VCDM spec itself.

**Review by awoie — APPROVED** [review]
lgtm

**Comment by TallTed** [comment]
@iherman — Why not make #1078 a suggested/requested change on #1076?

**Review by decentralgabe — APPROVED** [review]

**Review by dlongley — APPROVED** [review]

**Review by vongohren — APPROVED** [review]

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
Substantive, multiple reviews, changes requested and made (to other PRs), no objections, merging.

**Pull request merged**
