### PR TITLE
Changed the Media Type specifications to ignore HTTP link headers

### PR DESCRIPTION
**Pull request by iherman**
See the comment, and following discussion thread, in https://github.com/w3c/vc-data-integrity/pull/301#pullrequestreview-2217459301. This PR proposes a solution to those editorial issues.

(I have shamelessly reused the text used in the JSON-LD specification...)

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1539.html" title="Last updated on Aug 14, 2024, 3:23 PM UTC (a233ac0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1539/4c6005d...a233ac0.html" title="Last updated on Aug 14, 2024, 3:23 PM UTC (a233ac0)">Diff</a>

### CODE REVIEW

**Review by msporny — APPROVED** [review]

**Review by TallTed — COMMENTED** [review]
lgtm

**Review by dlongley — APPROVED** [review]

**Review by BigBlueHat — APPROVED** [review]

**Comment by TallTed** [comment]
"disallow" suggests "compliant software is not allowed to include `@context` info in those headers".

"ignore", on the other hand, permits delivery of `@context` info in those headers for purposes not related to VCs/VPs.

**Review by decentralgabe — APPROVED** [review]

**Review by longpd — APPROVED** [review]
This makes it clear what needs to be done with the new media type "application/vp".

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-08-14-vcwg#section3-1) on 2024-08-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.1. Changed the Media Type specifications to ignore HTTP link headers (pr vc-data-model#1539)

_See github pull request [vc-data-model#1539](https://github.com/w3c/vc-data-model/pull/1539)._




**Manu Sporny:** The PR is a suggestion that came up during a discussion in an issue that makes it clear that "we" (the VCWG and media types) that we specifically prohibit using a link header for a JSON-LD context and we do this because it externalizes the context and we don't have any use cases for the added complexity. Ivan indicated it would be a good idea to specifically call this out so this PR does that.  

**Ivan Herman:** Just to be precise, before, when we were using the hypothetical media type vc+ld+json -- then this remark was not necessary because JSON-LD spec has clear language on this.  
… Using HTTP for context was automatically disallowed. We changed the media type, this remark remained ineffective for our media type. I.e., it's a bit more than an extra note, it's setting the situation where we were before we changed the media type.  

**Brent Zundel:** this looks like its on track to be merged soon.  

</details>

**Review by msporny — APPROVED** [review]

**Pull request merged**
