### PR TITLE
making a note, a note

### PR DESCRIPTION
**Pull request by TallTed**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/722.html" title="Last updated on Jun 14, 2021, 2:23 PM UTC (cbf425a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/722/5422780...cbf425a.html" title="Last updated on Jun 14, 2021, 2:23 PM UTC (cbf425a)">Diff</a>

### CODE REVIEW

**Comment by burnburn** [comment]
The PR document has already been generated for the transition request.  Deferring.  If the editors believe this can safely be added before publication it will be.

**Comment by OR13** [comment]
suggest closing this PR / moving it back to an issue.

**Comment by TallTed** [comment]
The changes here are tiny, and probably considered editorial (as I believe the paragraph I styled as a non-normative NOTE here was meant to be such). The only objection to them in August 2019 was that the PR had already been generated; I think that's not currently a blocker.

**Comment by msporny** [comment]
> The changes here are tiny, and probably considered editorial (as I believe the paragraph I styled as a non-normative NOTE here was meant to be such). The only objection to them in August 2019 was that the PR had already been generated; I think that's not currently a blocker.

Agreed, waiting on process approval from @iherman.

**Review by msporny — APPROVED** [review]

**Review by kdenhartog — APPROVED** [review]

**Comment by msporny** [comment]
This can be merged.

**Review by awoie — APPROVED** [review]
lgtm

**Comment by kdenhartog** [comment]
Editorial, multiple positive reviews, no changes requested, no objections,
merging.

**Comment by kdenhartog** [comment]
No linked issue, so I'll leave the Errata label on here

**Pull request merged**
