### PR TITLE
Remove myself as editor

### PR DESCRIPTION
**Pull request by OR13**
https://lists.w3.org/Archives/Public/public-did-wg/2023Dec/0002.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1385.html" title="Last updated on Dec 13, 2023, 5:33 PM UTC (9212b86)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1385/40be9e0...9212b86.html" title="Last updated on Dec 13, 2023, 5:33 PM UTC (9212b86)">Diff</a>

### CODE REVIEW

**Review by decentralgabe — APPROVED** [review]

**Comment by TallTed** [comment]
Same question about `formerEditors` as elsewhere...

**Comment by msporny** [comment]
> Same question about `formerEditors` as elsewhere...

link? Or restate the question, please?

**Comment by OR13** [comment]
@msporny I assume the editors / authors list will be redone prior to publication, if at that time my name is still recommended by the algorithm, I have no objections to it being placed based on the data available.

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
> @msporny I assume the editors / authors list will be redone prior to publication, if at that time my name is still recommended by the algorithm, I have no objections to it being placed based on the data available.

Yes, correct.

I just found out that Echidna refuses to publish WDs if any of the Editor's are no longer in the WG:

https://github.com/w3c/vc-data-model/actions/runs/7225132498/job/19687907429#step:3:834

I'm going to have to merge this PR to get publications working again. I'll also need to move @awoie to `formerEditors` and deal w/ this later.

**Comment by msporny** [comment]
Purely editorial, merging to fix Echidna publication process.

**Pull request merged**
