### PR TITLE
Fix bug in `rdfs:range` of `verifiableCredential` property.

### PR DESCRIPTION
**Pull request by iherman**
Handles the bug described in #770

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/771.html" title="Last updated on Nov 14, 2021, 6:00 PM UTC (25a5c5e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/771/5d4e2b5...25a5c5e.html" title="Last updated on Nov 14, 2021, 6:00 PM UTC (25a5c5e)">Diff</a>

### CODE REVIEW

**Review by dlongley — APPROVED** [review]
LGTM

**Review by msporny — APPROVED** [review]

**Comment by brentzundel** [comment]
I don't think this change is normative, but I wonder if it is substantive. Would merging this PR cause implementations to break?

**Comment by kdenhartog** [comment]
Waiting to merge until @brentzundel is addressed

**Comment by brentzundel** [comment]
@dlongley or @msporny do you know the answer here: https://github.com/w3c/vc-data-model/pull/771#issuecomment-892738769 ?

**Comment by msporny** [comment]
This PR needs to be rebased before we merge it. I believe the same problem might apply to the `proof` property, but I haven't had the time to check to see if that's true yet.

**Comment by iherman** [comment]
This PR should not be merged in its current state; it should be re-engineered using the documentation generation tools and the respec must be refreshed, too. 

I will therefore close this PR without merge, and will work on a new PR to handle the issue. This will also take care of the rebase mentioned in https://github.com/w3c/vc-data-model/pull/771#issuecomment-1217924660.

Before closing, though... @msporny the `proof` property has definitely the same issue, but that is not a property defined in this vocabulary; it is defined in https://w3c-ccg.github.io/security-vocab/#proof. Yes, that one must be updated as well; is it a vocabulary that ought to be taken over by the WG?

**Comment by msporny** [comment]
@iherman wrote:
> is it a vocabulary that ought to be taken over by the WG?

Yes, it should be taken over by the WG.

**Pull request closed without merging**
