### PR TITLE
Add vocab terms for status list 2021

### PR DESCRIPTION
**Pull request by decentralgabe**
fixes the second part of #1134

### CODE REVIEW

**Comment by decentralgabe** [comment]
already in the context, but not the vocab https://github.com/w3c/vc-data-model/blob/main/contexts/credentials/v2#L117

**Review by brentzundel — APPROVED** [review]

**Review by msporny — APPROVED** [review]
Approving, noting that due to the change suggested by @mprorock that changes the index calculation, that we might need to rename StatusList2021 to StatusList2023. I know that Troy from Gen Digital had concerns about any breaking changes to StatusList2021 and requested that we not use the same type identifier there.

That, however, can be dealt with in a future PR, during CR if necessary (because of the at risk marker we have).

**Review by iherman — APPROVED** [review]

**Review by TallTed — CHANGES_REQUESTED** [review]
Editorial, trivial

**Review by brentzundel — APPROVED** [review]

**Review by dlongley — APPROVED** [review]

**Comment by decentralgabe** [comment]
Over a week, multiple approvals, changes addressed. Merging.

**Pull request merged**
