### PR TITLE
Add exp registered claim to v2 context 

### PR DESCRIPTION
**Pull request by OR13**
Basically same as: https://github.com/w3c/vc-data-model/pull/1221

### CODE REVIEW

**Review by decentralgabe — APPROVED** [review]

**Review by mprorock — APPROVED** [review]

**Review by dmitrizagidulin — APPROVED** [review]

**Review by msporny — CHANGES_REQUESTED** [review]
PR includes commits on main, needs a rebase.

**Review by davidlehn — CHANGES_REQUESTED** [review]
Extraneous commits should be removed so only the single relevant commit remains.

**Comment by OR13** [comment]
@davidlehn see same comment on https://github.com/w3c/vc-data-model/pull/1219#issuecomment-1665731653

**Review by brentzundel — APPROVED** [review]

**Comment by brentzundel** [comment]
@msporny and @davidlehn since this PR is quite simple (and the changes made were originally in a single commit) I think it should be fine to squash and merge back down to a single commit.

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
Normative, multiple reviews, no changes requested, no objections, merging.

**Pull request merged**
