### PR TITLE
Add cnf registered claim to v2 context

### PR DESCRIPTION
**Pull request by OR13**
This PR adds registered claim names used to ensure security properties to the v2 context.

```json
{
  "iss": "https://example.com/issuer",
  "iat": 1683000000,
  "exp": 1883000000,
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    {
    "@vocab": "https://ld.off.example#", 
    "cnf": {
      "@id": "https://www.iana.org/assignments/jwt#cnf",
      "@context": {
        "@protected": true,
        "kid": {
          "@id": "https://www.iana.org/assignments/jwt#kid",
          "@type": "@id"
        },
        "jwk": {
          "@id": "https://www.iana.org/assignments/jwt#jwk",
          "@type": "@json"
        }
      }
    }}
  ],
  "type": [
    "VerifiableCredential",
    "VaccinationCertificate"
  ],
  "issuer": "https://example.com/issuer",
  "issuanceDate": "2023-02-09T11:01:59Z",
  "expirationDate": "2028-02-08T11:01:59Z",
  "name": "COVID-19 Vaccination Certificate",
  "description": "COVID-19 Vaccination Certificate",
  "credentialSubject": {
    "vaccine": {
      "type": "Vaccine",
      "atcCode": "J07BX03",
      "medicinalProductName": "COVID-19 Vaccine Moderna"
    },
    "recipient": {
      "type": "VaccineRecipient"
    },
    "type": "VaccinationEvent",
    "order": "3/3",
    "dateOfVaccination": "2021-06-23T13:40:12Z"
  },
  "_sd_alg": "sha-256",
  "cnf": {
    "jwk": {
      "kty": "EC",
      "crv": "P-256",
      "x": "TCAER19Zvu3OHF4j4W4vfSVoHIP1ILilDls7vCeGemc",
      "y": "ZxjiWWbZMQGHVWKVQ4hbSIirsVfuecCE6t4jT9F2HZQ"
    }
  }
}
```

After this PR is merged, RDF compatible sd-jwt  vc's that include `cnf` claim will be labeled correctly, instead of adding incorrect term definitions for jwk / cnf...

```
...
_:c14n2 <https://www.iana.org/assignments/jwt#cnf> _:c14n4 .
_:c14n2 <https://www.w3.org/2018/credentials#credentialSubject> _:c14n3 .
_:c14n2 <https://www.w3.org/2018/credentials#expirationDate> "2028-02-08T11:01:59Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
_:c14n2 <https://www.w3.org/2018/credentials#issuanceDate> "2023-02-09T11:01:59Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
_:c14n2 <https://www.w3.org/2018/credentials#issuer> <https://example.com/issuer> .
_:c14n3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://ld.off.example#VaccinationEvent> .
_:c14n3 <https://ld.off.example#dateOfVaccination> "2021-06-23T13:40:12Z" .
_:c14n3 <https://ld.off.example#order> "3/3" .
_:c14n3 <https://ld.off.example#recipient> _:c14n1 .
_:c14n3 <https://ld.off.example#vaccine> _:c14n0 .
_:c14n4 <https://www.iana.org/assignments/jwt#jwk> "{\"crv\":\"P-256\",\"kty\":\"EC\",\"x\":\"TCAER19Zvu3OHF4j4W4vfSVoHIP1ILilDls7vCeGemc\",\"y\":\"ZxjiWWbZMQGHVWKVQ4hbSIirsVfuecCE6t4jT9F2HZQ\"}"^^<http://www.w3.org/1999/02/22-rdf-syntax-ns#JSON> .
```

### CODE REVIEW

**Review by dmitrizagidulin — APPROVED** [review]
:+1:

**Review by decentralgabe — APPROVED** [review]

**Review by mprorock — APPROVED** [review]

**Review by msporny — CHANGES_REQUESTED** [review]
PR includes commits on main, needs a rebase.

**Review by davidlehn — CHANGES_REQUESTED** [review]
Extraneous commits should be removed so only the single relevant commit remains.

**Comment by OR13** [comment]
@davidlehn I don't intend to apply your suggestion.

I recommend @msporny use the squash and merge feature, when merging PRs with commits caused due to rebasing issues.

**Comment by davidlehn** [comment]
> @davidlehn I don't intend to apply your suggestion.
> 
> I recommend @msporny use the squash and merge feature, when merging PRs with commits caused due to rebasing issues.

It would be nicer to do the quick PR fixes:
- git rebase -i
- [mark all the extraneous commits as 'd', apply, check result]
- git push -f

@msporny If you do need to squash, clean up the commit message to not include all the extra stuff.

**Review by brentzundel — APPROVED** [review]

**Comment by brentzundel** [comment]
@msporny and @davidlehn since this PR is quite simple (and the changes made were originally in a single commit) I think it should be fine to squash and merge back down to a single commit.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-08-09-vcwg#section2-7) on 2023-08-09

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.7. Add cnf registered claim to v2 context (pr vc-data-model#1219)

_See github pull request [vc-data-model#1219](https://github.com/w3c/vc-data-model/pull/1219)._




**Manu Sporny:** JWT stuff from Orie...  

**Oliver Terbu:** how to keep spec in sync with IANA registry.  

**Kristina Yasuda:** Orie only adding already registered.  

**Orie Steele:** has spoken with IANA folks; registries being updated, no timeline.  

> *Manu Sporny:* yes, what Orie said :).

> *Orie Steele:* Oliver, the same thing that happens today... you add a second context.

> *Manu Sporny:* correct ^.

**Oliver Terbu:** concern was publish, then new "claims" get registered; can we update context.  

**Kristina Yasuda:** not sure what claims your concerned about...  

> *Brent Zundel:* it is a problem for a future working group.

</details>

**Comment by msporny** [comment]
Normative, multiple reviews, no changes requested, no objections, merging.

**Review by msporny — APPROVED** [review]

**Pull request merged**
