### PR TITLE
(editorial) various clarified phrasings

### PR DESCRIPTION
**Pull request by TallTed**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/723.html" title="Last updated on Jun 14, 2021, 2:23 PM UTC (2cb9cae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/723/5422780...2cb9cae.html" title="Last updated on Jun 14, 2021, 2:23 PM UTC (2cb9cae)">Diff</a>

### CODE REVIEW

**Comment by burnburn** [comment]
The PR document has already been generated for the transition request. Deferring. If the editors believe this can safely be added before publication it will be.

**Comment by OR13** [comment]
suggest closing this PR / moving it back to an issue.

**Review by brentzundel — APPROVED** [review]

**Comment by msporny** [comment]
Waiting on process clarification from @iherman to merge.

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
This one is ready to be merged.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-06-14-vcwg#section4-3) on 2021-06-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.3. (editorial) various clarified phrasings (pr vc-data-model#723)

_See github pull request [#723](https://github.com/w3c/vc-data-model/pull/723)._




**Manu Sporny:** various clarified "phrases" - related to "JWT claims"  
… some details need to be review to make sure this does not impact, after it is determined it may/may not be merged  
… pr 723 is ready to go  

</details>

**Comment by kdenhartog** [comment]
Editorial, multiple positive reviews, no changes requested, no objections, merging.

**Comment by kdenhartog** [comment]
No linked issue for this leaving the Errata label on the PR

**Pull request merged**
