### PR TITLE
Fix markup

### PR DESCRIPTION
**Pull request by davidlehn**
An attempt to restore markup sanity.

~~Includes commit from https://github.com/w3c/vc-data-model/pull/321.  Pull that first.~~ (Removed commit.)

Quite possible this will cause conflicts in all other PRs.  If those are pulled in first I can update this PR.

***
<a href="https://pr-preview.s3.amazonaws.com/davidlehn/vc-data-model/pull/322.html" title="Last updated on Dec 20, 2018, 12:52 AM UTC (72de4ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/322/959241b...davidlehn:72de4ae.html" title="Last updated on Dec 20, 2018, 12:52 AM UTC (72de4ae)">Diff</a>

### CODE REVIEW

**Comment by msporny** [comment]
Merge conflicts due to a ton of PRs from @grantnoble ... please fix and I'll pull this in.

**Comment by davidlehn** [comment]
Updated.  Pulling this in may cause conflicts with some other PRs.  And looks like they often don't follow a strict whitespace and indent style.  Can fix those up later as things are merged.

**Comment by grantnoble** [comment]
@davidlehn, my apologies for stomping all over your changes with my PRs! If you tell me what style conventions we want (number of spaces/tabs before <p> tags, etc.) I can do this grunt work, leaving you to concentrate on the technical aspects of the doc.

**Comment by davidlehn** [comment]
@grantnoble No problem.  Some pain, but I'll live. ;-)  I'm rebasing right now and hopefully my changes get merged in before other people go and cause chaos again!

I guessed on a style.  Just wanted doc to be consistent one way or another.  Was doing 2 space indents for markup and code, blank lines before sections and various places, proper header levels, etc.

**Pull request merged**
