### PR TITLE
Clarified URIs may be references to verifiable data registry

### PR DESCRIPTION
**Pull request by brentzundel**
Signed-off-by: Brent <brent.zundel@gmail.com>

### CODE REVIEW

**Comment by ken-ebert** [comment]
+1 
By adding language to enable URIs to reference a verifiable data registry, the data model allows the Sovrin use case to occur.

**Comment by davidlehn** [comment]
Saying the properties are URIs should be enough to indicate the values can be DNS or non-DNS scheme based.  Why is this more specific new language needed?

**Comment by BigBlueHat** [comment]
@ken-ebert that's been the case from the beginning as URI's have always been in place in this spec--and in any JSON-LD-based data format fwiw.

Identifiers are not Locators, and Locators don't necessarily use DNS in their locating, so I'm concerned this particular content would be more confusing, not less.

URI is sufficiently defined in [RFC3986](https://tools.ietf.org/html/rfc3986), so perhaps what's needed here is some `<abbr>` tags around URI and a link to RFC3986 in the reference section.

**Comment by brentzundel** [comment]
I don't have a problem closing this PR if PR-265 is merged, as the examples added there clarify the issue sufficiently for me.

**Comment by msporny** [comment]
> I don't have a problem closing this PR if PR-265 is merged, as the examples added there clarify the issue sufficiently for me.

Waiting on @brentzundel to answer questions on #265 so we can merge that one. 

I suggest we close this PR as a URI does not mean DNS-rooted link so it's not necessary to point that out... I don't think we need to hold off on #265 (as I assume it'll be merged in some form or another that addresses what this PR was meant to address).

@brentzundel can we close this PR?

**Comment by brentzundel** [comment]
That is fine.

**Pull request closed without merging**
