### PR TITLE
Add privacy paragraph to introduction

### PR DESCRIPTION
**Pull request by brentzundel**
Part of resolution for Issue #237

### CODE REVIEW

**Comment by brentzundel** [comment]
Apologies, I linked my github account to my W3C account after submitting the pull request. Is there a way to re-run the ipr check?

**Comment by David-Chadwick** [comment]
Text looks OK to me

**Comment by msporny** [comment]
> Apologies, I linked my github account to my W3C account after submitting the pull request. Is there a way to re-run the ipr check?

Don't worry about it, I can override the check when merging. We know you're a part of the group.

**Comment by brentzundel** [comment]
Can we merge this one?

**Pull request merged**
