### PR TITLE
Add iat registered claim to v2 context

### PR DESCRIPTION
**Pull request by OR13**
This PR adds `iat` as a registered claim name to the v2 context.

Beware that `iat` aligns with `proof.created` in data integrity.

`iat` is not be be confused with `nbf` which is now called `validFrom`.

```json
{
  "@context": [
    "https://w3id.org/traceability/v1", {
    "iat": {
      "@id": "https://www.iana.org/assignments/jwt#iat",
      "@type": "https://www.w3.org/2001/XMLSchema#nonNegativeInteger"
    }
    }
  ],
  "type": "Organization",
  "name": "Bartell Inc 🔥",
  "description": "Realigned maximized alliance",
  "iat": 123
}
```

....

```
_:c14n0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://schema.org/Organization> .
_:c14n0 <https://schema.org/description> "Realigned maximized alliance" .
_:c14n0 <https://schema.org/name> "Bartell Inc 🔥" .
_:c14n0 <https://www.iana.org/assignments/jwt#iat> "123"^^<https://www.w3.org/2001/XMLSchema#nonNegativeInteger> .
```

### CODE REVIEW

**Review by dmitrizagidulin — APPROVED** [review]
:+1:

**Review by decentralgabe — APPROVED** [review]

**Review by msporny — CHANGES_REQUESTED** [review]
PR includes commits on main, needs a rebase.

**Review by davidlehn — CHANGES_REQUESTED** [review]
Extraneous commits should be removed so only the single relevant commit remains.

**Comment by OR13** [comment]
@davidlehn see same comment on https://github.com/w3c/vc-data-model/pull/1219#issuecomment-1665731653

**Review by brentzundel — APPROVED** [review]

**Comment by brentzundel** [comment]
@msporny and @davidlehn since this PR is quite simple (and the changes made were originally in a single commit) I think it should be fine to squash and merge back down to a single commit.

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
Normative, multiple reviews, no changes requested, no objections, merging.

**Pull request merged**
