### PR TITLE
Fixed dead link to CL paper

### PR DESCRIPTION
**Pull request by etaleo**
The [old link](https://groups.csail.mit.edu/cis/pubs/lysyanskaya/cl02b.pdf) to the CL signature paper is dead, so I have replaced it with a link to [the paper at researchgate.net](https://www.researchgate.net/publication/220922101_A_Signature_Scheme_with_Efficient_Protocols).

### CODE REVIEW

**Comment by etaleo** [comment]
Additional info:

I [searched](https://www.google.com/search?hl=en&q=cl02b.pdf) for a .pdf with the same name "cl02b.pdf" as in the dead link and found e.g. [this one](http://infosec.pusan.ac.kr/wp-content/uploads/2019/03/cl02b.pdf) and cross-checked to see if the [paper at researchgate](https://www.researchgate.net/publication/220922101_A_Signature_Scheme_with_Efficient_Protocols) is really referring to the same paper as the old dead link

**Review by TallTed — APPROVED** [review]
LGTM

**Review by msporny — APPROVED** [review]

**Comment by kdenhartog** [comment]
This looks good and has a substantive number of reviews. To error on the safe side of things though, I'll refrain from merging now until we can notify the CCG mailing list and trigger the 14 day review period for this PR. I'll go ahead and merge once that requirement of the review process is met.

**Comment by brentzundel** [comment]
@kdenhartog as an editor you are fully authorized to notify the ccg about any PRs that you feel are ready to merge and start the 14-day clock. We could also create a `14 day merge` label so we know that the ccg has been notified.

**Comment by kdenhartog** [comment]
Thanks for clarification. In this case, the "error on the side of caution" was more about not merging right away even though it's sat long enough and had multiple positive reviews. I figured in order to make things a bit smoother on reviewers I'd finish getting the group of PRs together and then will trigger that process with an email to the CCG mailing list. I still have a few more PRs I want to get in to group with those however so going to finish those up and then send it out. Hopefully I can get to that by today.

**Comment by wyc** [comment]
@kdenhartog were you able to send this email, or would you like help in doing so?

**Review by dlongley — APPROVED** [review]

**Comment by kdenhartog** [comment]
multiple positive reviews, no objections, merging

**Comment by kdenhartog** [comment]
There's no linked issue for this, leaving the Errata and Editorial labels on the PR

**Pull request merged**
