### PR TITLE
Changes for privacy respecting credentials

### PR DESCRIPTION
**Pull request by lovesh**
***
<a href="https://pr-preview.s3.amazonaws.com/sovrin-foundation/vc-data-model/pull/208.html" title="Last updated on Aug 7, 2018, 10:54 AM GMT (263935d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/208/b0c29e5...sovrin-foundation:263935d.html" title="Last updated on Aug 7, 2018, 10:54 AM GMT (263935d)">Diff</a>

### CODE REVIEW

**Comment by dlongley** [comment]
@lovesh,

1. We need an IPR commitment from you/your organization before we can do anything else. Please click the [details](https://labs.w3.org/hatchery/repo-manager/pr/id/w3c/vc-data-model/208) link above.

2. This PR has both substantive and editorial changes, could you please split this into two separate PRs for that? Also -- this PR is based off of an old version of the spec, so you'll need to rebase it before doing anything else.

Thanks!

**Comment by lovesh** [comment]
@dlongley 
1) Do you need the IPR commitment from the authors of the commit or the organisation? I can consolidate the commits.
2) Can you give an example of "editorial changes"? I merged the latest `gh-pages`.

**Comment by dlongley** [comment]
@lovesh,

> Do you need the IPR commitment from the authors of the commits or the organisation of the committer? I can consolidate the commits.

You need to link any github accounts that committed with an appropriate W3C account. See the instructions on the link for how to do that.

> Can you give an example of "editorial changes"? I merged the latest gh-pages.

Editorial changes are those that merely clean up the language/sentence structure, fix grammar/spelling mistakes, improve explanations, so on.

It's much easier to pull those in if they aren't mixed into the rest of the changes that are more substantive. Substantive changes may be controversial and require some back and forth discussion with the group. It would be best not to hold up editorial fixes on account of those, particularly because this often leads to more work later with additional rebasing and so on because the spec continues to evolve asynchronously.

**Comment by lovesh** [comment]
Alright, i linked my github account an hour ago and it shows that my account is linked on the W3C page but on the "Repository Manager", it shows that "lovesh is unknown, they need to link their Github account with a W3C account.". Does it take some time?
I would say most of our changes are substantive, i will take another look but i am doubtful that even 5% of our changes are editorial.

**Comment by dlongley** [comment]
@lovesh,

> Alright, i linked my github account an hour ago and it shows that my account is linked on the W3C page but on the "Repository Manager", it shows that "lovesh is unknown, they need to link their Github account with a W3C account.". Does it take some time?

The github hook probably needs to run again -- which it will if you push another commit here. I don't have admin access to force it to run.

> I would say most of our changes are substantive, i will take another look but i am doubtful that even 5% of our changes are editorial.

At a glance it seems like most of the prose changes are editorial, especially all of the text that is not specific to ZKPs. I think we could get consensus to pull in non-ZKP related prose (i.e. pretty much everything but example changes and new text related to those changes) pretty quickly -- and it would save you additional rebasing if we need to wait to discuss the other changes. Another option is to break each specific change into a separate PR so the group can more easily review and make iterative progress.

As it stands, it will be difficult for the group to review this entire PR (it is quite lengthy and github even disables viewing the diff by default) and say whether or not to accept it as a whole. Just looking at it myself, I immediately noticed some good improvements to the existing spec we'd want to pull in (editorial) and some other bits that I know the group will need to discuss (substantive changes like eliminating `proof`, changing the model for `claim`, adding `this`, so on).

**Comment by dlongley** [comment]
@lovesh,

It also looks like there are other committers that may not have their github accounts linked to W3C accounts. Anyone that committed in this PR will need to do so.

**Comment by ChristopherA** [comment]
First off, I wanted to say that I'm impressed with this PR!

However, I too have been trying to go through and review this PR and am finding the number of changes (736) intimidating. Like @dlongley I agree that it should be broken up a bit. I personally would like to see the editorial changes broken up in major sections (11 of them) so that we can review each section with thoughts on best language. Then more substantive things like changes to model of claim, proof, etc. should be separate. Finally, I suggest the zkp stuff should be separate.

**Comment by lovesh** [comment]
The request to split the PR into pieces makes sense, and we can try to accommodate. However, just as evaluating the PR is a big task, so was creating it. It represents hundreds of hours of detailed analysis. Making an additional investment of hundreds more hours of reformatting/restructuring is difficult to justify if ideas are unlikely to be accepted, so we've made a brief, numbered catalog of the PR's ideas. We'd like to get some reaction to those ideas to help us know where to focus. Here is a [summary](https://docs.google.com/document/d/10e6lcsX0kiXkWX4_79hD1fb4p_AbFGsRm90eJJKFayI/edit) of the PR; could you review and call out ideas to give us guidance, as in "6.a is uncontroversial and likely to be accepted; 5.a and 5.b were already discussed in a previous call and voted against by the community."?

**Comment by msporny** [comment]
Closing this PR as it's being subsumed by other smaller, more focused PRs.

**Pull request closed without merging**
